### ISSUE TITLE
Implement rest of the cryptocurrencies

### ISSUE THREAD

**Issue by mubaris** [gostudent/Grypto#3]
API Documentation - https://coinmarketcap.com/api/

- [ ] Ethereum
- [ ] Ripple
- [ ] Bitcoin Cash
- [ ] Carnado
- [ ] LiteCoin

One Cryptocurrency per person

**Comment by Jigar3** [comment]
I want to take this issue.
I am implemeting Ethereum

**Comment by Jigar3** [comment]
@mubaris should I proceed with a pr

**Comment by mubaris** [comment]
Yep

**Comment by rahulkumaran** [comment]
I'd like to implement this for Bitcoin Cash

**Comment by rahulkumaran** [comment]
I'd actually like to implement it for everything that's left
SO basically I'll be implementing it for BCH,XRP,LTC and ADA

**Comment by mubaris** [comment]
If you're doing everything, Use simple API call. The main one
