### ISSUE TITLE
Add Rupee Sign along with Price

### ISSUE THREAD

**Issue by mubaris** [gostudent/Grypto#4]

**Comment by rahulkumaran** [comment]
I'd like to work on this :) can you assign this to me?

**Comment by mubaris** [comment]
Don't need to worry about assigning. Just comment and start working on it 😄

**Comment by rahulkumaran** [comment]
Haha I'll take care of that from next time!
Thanks @mubaris

**Comment by rahulkumaran** [comment]
Haha I'll take care of that from next time!
Thanks @mubaris
